[package]
name = "qubit-ioc"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-ioc"
homepage = "https://qubit-ltd.github.io/rs-ioc/"
description = "Application-level component assembly and sharing for Rust applications"
readme = "README.md"
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/src/**",
    "/docs/**",
    "/tests/**",
    "/benches/**",
]

[lib]
name = "qubit_ioc"
